[package]
name = "fenrir-rendering"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
fenrir-core = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
glow = { workspace = true }
euclid = { workspace = true }
winit = { workspace = true }

# Servo embedding API
servo = { workspace = true }
surfman = { version = "0.11.0", features = ["chains"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
anyhow = { workspace = true }
